name: Test and Deploy to Render

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Start Firebase Emulator Suite
        run: |
          firebase emulators:start --only firestore,auth --project project-id &
          sleep 15

      - name: Dar permiso de ejecución a gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test
