name: Backend

on: [push]

jobs:
  build:
    name: My Job
    runs-on: ubuntu-latest
    env:
      SECRET_PASS_DECRYPTION_KEY: ${{ secrets.SECRET_PASS_DECRYPTION_KEY }}
      
    steps:
      - name: Read a variable
        run: echo "${{SECRET_PASS_DECRYPTION_KEY}}"
