name: Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        env:
          SECRET_PASS_DECRYPTION_KEY: ${{ secrets.SECRET_PASS_DECRYPTION_KEY }}
        run: |
          echo "${{SECRET_PASS_DECRYPTION_KEY}}"
