name: Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Give permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Show environment variables
        run: env
      
      - name: Run with Gradle
        run: |
          export SECRET_PASS_DECRYPTION_KEY="${{ secrets.SECRET_PASS_DECRYPTION_KEY }}"
          ./gradlew build --no-daemon
