name: Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_PASS_DECRYPTION_KEY: ${{ secrets.SECRET_PASS_DECRYPTION_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Give permission to Gradle wrapper
        run: chmod +x gradlew
      
      - name: Run with Gradle and secret
        run: ./gradlew build --no-daemon
