name: Backend

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret
        uses: actions/cache@v4
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
